import { useState } from "react";
import { useCanteiro } from "../../layouts/CanteiroLayout";
import ObraCard from "../../componentes/canteiro/ObraCard";
export default function HistoricoObras() {
  const { obras, selecionarObra, onNavegar, carregando } = useCanteiro();
  const [busca, setBusca] = useState(""), [status, setStatus] = useState(""), [categoria, setCategoria] = useState("");
  const lista = obras.filter(o => (!status || o.status === status) && (!categoria || o.categoria === categoria) && [o.nome, o.endereco, o.localizacao].filter(Boolean).join(' ').toLocaleLowerCase("pt-BR").includes(busca.toLocaleLowerCase("pt-BR")));
  return <><div className="ct-title"><span className="ct-eyebrow">PORTFÓLIO DE CAMPO</span><h1>Histórico de Obras</h1><p>Selecione uma obra para consultar seus detalhes e registros.</p></div><div className="ct-stack"><section className="ct-card ct-stack"><label className="ct-field">Buscar obra<input type="search" value={busca} onChange={e => setBusca(e.target.value)} placeholder="Nome ou localização" /></label><div className="ct-grid"><label className="ct-field">Status<select value={status} onChange={e => setStatus(e.target.value)}><option value="">Todos</option>{[...new Set(obras.map(o => o.status).filter(Boolean))].map(s => <option key={s}>{s}</option>)}</select></label><label className="ct-field">Categoria<select value={categoria} onChange={e => setCategoria(e.target.value)}><option value="">Todas</option>{[...new Set(obras.map(o => o.categoria).filter(Boolean))].map(c => <option key={c}>{c}</option>)}</select></label></div></section>{lista.map(obra => <ObraCard key={obra.id_obra} obra={obra} titulo="OBRA" onAbrir={() => { selecionarObra(obra.id_obra); onNavegar("canteiro-obra"); }} />)}{!carregando && !lista.length && <p className="ct-card">Nenhuma obra encontrada para estes filtros.</p>}</div></>;
}
