import { useCanteiro } from "../../layouts/CanteiroLayout";
import EstadoObra from "../../componentes/canteiro/EstadoObra";
import ObraCard from "../../componentes/canteiro/ObraCard";
import RegistroCard from "../../componentes/canteiro/RegistroCard";
import PendenciaCard from "../../componentes/canteiro/PendenciaCard";
import Icone from "../../componentes/canteiro/Icone";
import { hoje, formatarData, ocorrenciasDiarios } from "../../canteiro/dados";
export default function HomeCanteiro() {
  const { usuario, obra, diarios, onNavegar, rascunhos, avisos, apontamentos, carregando, recursos } = useCanteiro();
  const ocorrencias = ocorrenciasDiarios(diarios);
  const pendentes = rascunhos.filter(r => String(r.obra) === String(obra?.id_obra));
  return <><div className="ct-title"><span className="ct-eyebrow">OPERAÇÃO DIÁRIA · {formatarData(hoje())}</span><h1>Olá, {usuario.nome.split(" ")[0] || "equipe"}.</h1><p>Seu dia de trabalho, em um só lugar.</p></div><EstadoObra>{obra && <div className="ct-stack"><ObraCard obra={obra} diario={diarios[0]} onAbrir={() => onNavegar("canteiro-obra")} /><section className="ct-card"><h2>Resumo do dia</h2>{carregando ? <p role="status">Carregando resumo…</p> : <><p>Atividades registradas: {avisos.some(a => a.includes("apontamentos") || a.includes("diários")) ? "Indisponível" : apontamentos.filter(a => String(a.data).slice(0, 10) === hoje()).length}</p><p>Diários do dia: {avisos.some(a => a.includes("diários")) ? "Indisponível" : diarios.filter(d => String(d.data).slice(0, 10) === hoje()).length}</p><p>Rascunhos pendentes: {pendentes.length}</p></>}</section><section className="ct-card"><h2>Recursos da obra</h2><dl className="ct-resource-summary">{[["equipes", "Equipes"], ["insumos", "Materiais / Insumos"], ["maquinarios", "Maquinários"]].map(([tipo, titulo]) => <div key={tipo}><dt>{titulo}</dt><dd>{avisos.some(a => a.includes("recursos")) ? "Não informado" : recursos[tipo].length}</dd></div>)}</dl></section><section><h2 className="ct-section-title">Ações rápidas</h2><div className="ct-actions">{[["atividade", "Registrar atividade"], ["ocorrencia", "Registrar ocorrência"], ["material", "Registrar material"], ["foto", "Tirar foto"], ["diario", "Abrir Diário de Obra"]].map(([tipo, titulo]) => <button type="button" key={tipo} className="ct-action" onClick={() => onNavegar(`canteiro-${tipo}`)}><Icone nome={tipo === "ocorrencia" ? "pendencias" : tipo} /><span>{titulo}</span><Icone nome="seta" /></button>)}</div></section><section className="ct-stack"><div className="ct-row"><h2>Pendências e ocorrências</h2><button type="button" className="ct-link" onClick={() => onNavegar("canteiro-pendencias")}>Ver todas</button></div><p className="ct-muted">{pendentes.length} rascunho(s) local(is) desta obra, aguardando envio.</p>{ocorrencias.slice(0, 2).map(item => <PendenciaCard key={item.id} item={item} />)}{!ocorrencias.length && !avisos.includes("Não foi possível carregar diários.") && <p className="ct-muted">Nenhum atraso ou paralisação registrado nos diários disponíveis.</p>}</section><section className="ct-stack"><div className="ct-row"><h2>Diários recentes</h2><button type="button" className="ct-link" onClick={() => onNavegar("canteiro-registros")}>Histórico</button></div>{diarios.slice(0, 3).map(d => <RegistroCard key={d.id_diario} diario={d} onAbrir={() => onNavegar("canteiro-registros")} />)}{!diarios.length && !avisos.some(a => a.includes("diários")) && <p className="ct-muted">Nenhum diário disponível.</p>}</section></div>}</EstadoObra></>;
}
