import useRegistro from "../../canteiro/useRegistro";
import { salvarAtividade, formatarData } from "../../canteiro/dados";
import EstadoObra from "../../componentes/canteiro/EstadoObra";
import { Campo, Mensagens, AcoesRegistro } from "../../componentes/canteiro/FormularioBase";
import ProgressBar from "../../componentes/canteiro/ProgressBar";
const inicial = () => ({ diario_id: "", atividade_eap_id: "", percentual_dia: "", url_foto: "" });
export default function RegistrarAtividade() {
  const r = useRegistro("atividade", inicial), { ctx, form, campo } = r;
  function validar() {
    if (!ctx.diarios.some(d => String(d.id_diario) === String(form.diario_id))) throw new Error("Selecione um diário desta obra.");
    if (!ctx.atividades.some(a => String(a.id_atividade) === String(form.atividade_eap_id))) throw new Error("Selecione uma atividade desta obra.");
    if (form.percentual_dia === "" || !Number.isFinite(Number(form.percentual_dia)) || Number(form.percentual_dia) <= 0 || Number(form.percentual_dia) > 100) throw new Error("Informe um progresso maior que zero e de até 100%.");
    if (form.url_foto) { let url; try { url = new URL(form.url_foto); } catch { throw new Error("Informe um endereço válido para a foto."); } if (!["http:", "https:"].includes(url.protocol)) throw new Error("Use um endereço HTTP ou HTTPS para a foto."); }
  }
  return <><div className="ct-title"><span className="ct-eyebrow">EVOLUÇÃO FÍSICA</span><h1>Registrar atividade</h1><p>Informe o percentual executado no dia.</p></div><EstadoObra><form className="ct-stack" onSubmit={e => r.enviar(e, validar, salvarAtividade, { percentual_dia: Number(form.percentual_dia), diario_id: Number(form.diario_id), atividade_eap_id: Number(form.atividade_eap_id), url_foto: form.url_foto.trim() })}><section className="ct-card ct-stack"><label className="ct-field">Diário de Obra<select value={form.diario_id} disabled={r.salvando || ctx.carregando} onChange={e => campo("diario_id", e.target.value)}><option value="">Selecione um diário</option>{ctx.diarios.map(d => <option key={d.id_diario} value={d.id_diario}>{formatarData(d.data)} · {d.turno} · #{d.id_diario}</option>)}</select></label>{!ctx.carregando && !ctx.diarios.length && <p>Cadastre um Diário de Obra antes de registrar a atividade.</p>}<label className="ct-field">Atividade<select value={form.atividade_eap_id} disabled={r.salvando || ctx.carregando} onChange={e => campo("atividade_eap_id", e.target.value)}><option value="">Selecione uma atividade</option>{ctx.atividades.map(a => <option key={a.id_atividade} value={a.id_atividade}>{a.descricao}</option>)}</select></label>{!ctx.carregando && !ctx.atividades.length && <p>Não há atividades disponíveis. O cadastro de atividades permanece no Escritório.</p>}<Campo form={form} campo={campo} disabled={r.salvando} nome="percentual_dia" titulo="Progresso executado no dia (%)" type="number" min="0.01" max="100" step="0.01" inputMode="decimal" /><ProgressBar valor={form.percentual_dia} /><Campo form={form} campo={campo} disabled={r.salvando} nome="url_foto" titulo="Endereço de foto já publicada (opcional)" type="url" maxLength={512} /><p className="ct-muted">O apontamento aceita um endereço de foto, mas não permite upload nem observação. Registre atrasos e paralisações no diário.</p></section><Mensagens erro={r.erro} mensagem={r.mensagem} /><AcoesRegistro registro={r} /></form></EstadoObra></>;
}
