const CLIENT_DB_ERROR_CODES = new Set([
  "ER_BAD_NULL_ERROR",
  "ER_NO_REFERENCED_ROW",
  "ER_NO_REFERENCED_ROW_2",
  "ER_ROW_IS_REFERENCED",
  "ER_ROW_IS_REFERENCED_2",
  "ER_DUP_ENTRY",
  "ER_TRUNCATED_WRONG_VALUE",
  "ER_TRUNCATED_WRONG_VALUE_FOR_FIELD",
  "WARN_DATA_TRUNCATED",
  "ER_DATA_TOO_LONG",
  "ER_WRONG_VALUE_COUNT_ON_ROW",
  "ER_NON_DEFAULT_VALUE_FOR_GENERATED_COLUMN",
  "ER_CHECK_CONSTRAINT_VIOLATED"
]);

function dbStatus(err) {
  return CLIENT_DB_ERROR_CODES.has(err?.code) ? 400 : 500;
}

module.exports = { dbStatus };
